### PR TITLE
Add docker.elastic.co support for elasticsearch images

### PR DESCRIPTION
**Pull request by danielebarbaro**
Hi! 
This PR solve #76 .

Official **elasticsearch** images are in _https://www.docker.elastic.co/r/elasticsearch_.
The problem was that _https://docker.elastic.co/v2/elasticsearch/elasticsearch/tags/list needs_ an `access_token`.

I wrote some lines of code to catch a valid `access_token` before call tag list url.

### CODE REVIEW

**Comment by abenettt** [comment]
This looks great!
Do you know how long the access token is valid for? Maybe if it is for long enough we could cache it for a time so we don't have to request it always.

**Comment by danielebarbaro** [comment]
Hi @abenettt, unfortunately there's no `expire_in` field on auth response.

I've been thinking about saving the token somewhere but you need to take a valid token only when you create a new container.

**Comment by abenettt** [comment]
Ah yeah you're right it would not really make sense to save the token.

**Comment by danielebarbaro** [comment]
hi, @josecanhelp @mattstauffer I just updated the PR just to keep branch cleaned. Feel free to discard this PR

**Comment by josecanhelp** [comment]
Great work, @danielebarbaro. Thanks!

**Pull request merged**
