### PR TITLE
add disk usage command

### LINKED ISSUE #124: Add a wrapper for `docker system df` to check disks space usage

### PR DESCRIPTION
**Pull request by mihaileu**
resolve #124 

lmk if this is what you want here

### CODE REVIEW

**Review by josecanhelp — APPROVED** [review]
@mattstauffer can you give this a once-over since you created the initial issue? 

It works well for me.
image

**Comment by mattstauffer** [comment]
This looks great! The only issue is that it's not filtering over *only* the Takeout containers, which we would probably want, right? Or is that not even possible?

**Comment by mihaileu** [comment]
Is not possible :)

**Comment by danielebarbaro** [comment]
Hi @mihaileu, I know it's insane but you can try -v option combined with format grep and regex 🤣

**Comment by mihaileu** [comment]
Sounds kinky, I could try regex is my second love

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mattstauffer** [comment]
Hey @mihaileu, any news on whether you might have time to work on this? Let me know if you're too busy. Thanks!

**Comment by mihaileu** [comment]
Hi @mattstauffer, currently I do not have time to work on this. We can close this an re-open sometime.

**Comment by mattstauffer** [comment]
@mihaileu No worries, I'll take a peek at it myself. Thanks! And thanks for your work!

**Pull request closed without merging**
