### PR TITLE
Add traefik service

### PR DESCRIPTION
**Pull request by viicslen**
Adds [traefik](https://doc.traefik.io/traefik/) reverse proxy to the list of available services

### CODE REVIEW

**Comment by mattstauffer** [comment]
In one of your comments you wrote this: 

```
// Cannot use $_SERVER superglobal since that's empty during UnitUnishTestCase;
```

What do you mean by `UnitUnishTestCase`?

**Comment by mattstauffer** [comment]
Ha! OK, I'll remove.

**Comment by viicslen** [comment]
> Extracted and re-wrote here: [6eda6b5](https://github.com/tighten/takeout/commit/6eda6b577134041657f33d7e61feaba0ceb44f14)

Yeah, that looks much better.

BTW, I'm not too sure but I think the Windows directory separator should also be included when trimming the trailing slash in the following line:
https://github.com/tighten/takeout/blob/6eda6b577134041657f33d7e61feaba0ceb44f14/app/Shell/Environment.php#L77

**Comment by mattstauffer** [comment]
whoops, thanks! i missed that.

**Pull request merged**
