### PR TITLE
Add tests for disable command

### PR DESCRIPTION
**Pull request by olivernybroe**
I have added some tests for the disable command, together with selecting things with the menu.

If the testing of menu is acceptable, then I wouldn't mind fixing the test marked `incomplete` also.

### CODE REVIEW

**Comment by olivernybroe** [comment]
So I realised that while I created my pr, tests for the disable command was added in.

However those tests did not do anything at all, as it tried to mock the command itself which does not work.
So all of the expectations written in the mock of the command were useless. You can test it quickly by for example making tight expectations, like expecting that a certain method was only called once.

**Comment by mattstauffer** [comment]
@olivernybroe Thanks for the updated note! Would you mind updating this PR so it doesn't have a merge conflict and then I'd be really happy to review it? Thanks so much!

**Comment by olivernybroe** [comment]
@mattstauffer of course 👍 

I have removed the merge conflicts

**Comment by mattstauffer** [comment]
Thanks @olivernybroe!

**Pull request merged**
